Description = "Narwhal is a modern IRC bot written in Go."
License = "Apache-2.0"
Name = "Narwhal"
Version = 0.1

[Projects]
	[Projects.narwhal]
		Binary = true
		Destination = "build/narwhal"
		DisableNestedEnvironment = true
		EnableGoModules = true
		Plugin = "go"
		Private = ["github.com"] # Ignore github.com caching since updating Narwhal against tusk can be time sensitive
		Source = "*.go"
		Type = "binary"
